### ISSUE TITLE
Pingo hijacks flags

### ISSUE THREAD

**Issue by ysimonson** [dullgiulio/pingo#3]
If you use pingo in combination with a library that acts as a substitute for `flags` (e.g. [cli](https://github.com/codegangsta/cli) ), the application flags get overriden by pingo's. This happens even if you just import pingo.

As far as I can tell, this is due to [this line](https://github.com/dullgiulio/pingo/blob/master/server.go#L80), in combination with pingo's use of flags in `makeConfig()`.

Would you accept a PR that refactored to ensure pingo is side-effect-free, and that a configuration could be passed in?

**Comment by dullgiulio** [comment]
Sure, feel free to open the PR.

**Comment by ysimonson** [comment]
Hm, this seems like a more involved PR that I originally thought. Will have to re-approach later.

**Comment by dullgiulio** [comment]
I definitely see a problem with my parsing flags in `makeConfig()`. I pushed a branch `parse-flags-once` to address this.

It fixes the problem with the `flags` package, but I guess not with other packages like `cli`. But maybe this is the right direction?

It's also possible that we just don't support other flags parsing libraries, after all these are internal plugins, not user tools.

**Comment by ysimonson** [comment]
Could you push the branch to github?

**Comment by ysimonson** [comment]
Oops nm, I see it's been merged into master
