### ISSUE TITLE
Feature request - integrate with bindata

### ISSUE THREAD

**Issue by aliafshar** [dullgiulio/pingo#5]
Wouldn't it be neat to integrate with bindata or other binary embedding tech? Executables could be reconstructed and executed without needing to know paths.

**Comment by dullgiulio** [comment]
Nice idea, however, I think it would be best to solve it in another package. For one thing, it has some heuristics to implement.

To execute the embedded binaries you still need to write them down to the filesystem somewhere. Where? Maybe not in the temp files, there executables might not be allowed. So I guess for that too we might need user conf.
